/*
 *  cindexmenuitems.h
 *  Cindex
 *
 *  Created by PL on 2/12/05.
 *  Copyright 2005 Indexing Research. All rights reserved.
 *
 */

/* Menu item tags */

#define MENUMASK(A) (((int)(A)/100)*100)
enum {		// CINDEX menu
	MIM_CINDEX = 00,
    MI_PREFS = (MIM_CINDEX+1),
	MI_CHECKUPDATE = (MIM_CINDEX+2),
};

enum {		// FILE menu
	MIM_FILE = 100,
    MI_NEW = (MIM_FILE+1),
    MI_OPEN = (MIM_FILE+2),
    MI_RECENT = (MIM_FILE+3),
    MI_CLOSE = (MIM_FILE+4),
    MI_SAVE = (MIM_FILE+5),
    MI_SAVEAS = (MIM_FILE+6),
    MI_SAVECOPYAS = (MIM_FILE+7),
  	MI_REVERT = (MIM_FILE+8),
	MI_SAVESTYLESHEET = (MIM_FILE+9),
    MI_IMPORT = (MIM_FILE+10),
    MI_NEWGROUP = (MIM_FILE+11),
    MI_SAVEGROUP = (MIM_FILE+12),
	MI_PRINT = (MIM_FILE+13),
	MI_PAGESETUP = (MIM_FILE+14),
};

enum {		// EDIT menu
	MIM_EDIT = 200,
    MI_UNDO = (MIM_EDIT+1),
    MI_REDO = (MIM_EDIT+2),
    MI_CUT = (MIM_EDIT+3),
    MI_COPY = (MIM_EDIT+4),
    MI_PASTE = (MIM_EDIT+5),
    MI_DELETE = (MIM_EDIT+6),
    MI_SELECTALL = (MIM_EDIT+7),
    MI_NEWRECORD = (MIM_EDIT+8),
    MI_EDITRECORD = (MIM_EDIT+9),
    MI_DUPLICATE = (MIM_EDIT+10),
	MI_DEMOTE = (MIM_EDIT+18),
    MI_DELETED = (MIM_EDIT+11),
    MI_LABELED = (MIM_EDIT+12),
    MI_NEWABBREV = (MIM_EDIT+13),
    MI_FIND = (MIM_EDIT+14),
    MI_FINDAGAIN = (MIM_EDIT+15),
    MI_REPLACE = (MIM_EDIT+16),
    MI_SPELL = (MIM_EDIT+17),
	
	MI_REMOVEMARK = (MIM_EDIT+19),
};

enum {		// VIEW menu
	MIM_VIEW = 300,
	MI_GOTO = (MIM_VIEW+1),
	MI_VIEWALL = (MIM_VIEW+2),
	MI_NEWRECORDS = (MIM_VIEW+3),
	MI_GROUPMENU = (MIM_VIEW+4),
	MI_TEMPORARYGROUP = (MIM_VIEW+5),
	MI_FULLFORMAT = (MIM_VIEW+6),
	MI_DRAFTFORMAT = (MIM_VIEW+7),
	MI_SUMMARYFORMAT = (MIM_VIEW+8),
	MI_UNFORMATTED = (MIM_VIEW+9),
	MI_HIDEBYATTRIBUTE = (MIM_VIEW+10),
	MI_SHOWNUMBERS = (MIM_VIEW+11),
	MI_VIEWDEPTHMENU = (MIM_VIEW+12),
	MI_WRAPLINES = (MIM_VIEW+13),
	MI_SHOWSORTED = (MIM_VIEW+14),
};

enum {
	MI_GROUP = (MIM_VIEW+30),
	MI_DEPTH = (MIM_VIEW+31),
};

enum {		// FORMAT menu
	MIM_FORMAT = 400,
	MI_SHOWFONT = (MIM_FORMAT+1),
	MI_PLAIN = (MIM_FORMAT+2),
//	MI_BOLD = (MIM_FORMAT+3),
//	MI_ITALIC = (MIM_FORMAT+4),
	MI_BOLD = 2,
	MI_ITALIC = 1,
	MI_UNDERLINE = (MIM_FORMAT+5),
	MI_SMALL = (MIM_FORMAT+6),
	MI_SUPER = (MIM_FORMAT+7),
	MI_SUB = (MIM_FORMAT+8),
	MI_INITIALCAP = (MIM_FORMAT+9),
	MI_UPPERCASE = (MIM_FORMAT+10),
	MI_LOWERCASE = (MIM_FORMAT+11),
	MI_ALIGNMENT = (MIM_FORMAT+12),
};

enum {		// Record context menu
	/* cut, copy paste */
	MI_FONTLIST = (MIM_FORMAT+50),
	MI_BRACES = (MIM_FORMAT+51),
	MI_BRACKETS = (MIM_FORMAT+52),
	MI_SWAPPARENS = (MIM_FORMAT+53),
	MI_EMBED_RL = (MIM_FORMAT+54),

	MI_DEFAULTFONT = (MIM_FORMAT+60),
};

enum {		// DOCUMENT menu
	MIM_DOCUMENT = 500,
	MI_MARGINCOL = (MIM_DOCUMENT+1),
	MI_HEADFOOT = (MIM_DOCUMENT+2),
	MI_GROUPENTRIES = (MIM_DOCUMENT+3),
	MI_STYLELAYOUT = (MIM_DOCUMENT+4),
	MI_HEADINGS = (MIM_DOCUMENT+5),
	MI_CROSSREFS = (MIM_DOCUMENT+6),
	MI_PAGEREFS = (MIM_DOCUMENT+7),
	MI_STYLED = (MIM_DOCUMENT+8),
	MI_RECSTRUCTURE = (MIM_DOCUMENT+9),
	MI_REFSYNTAX = (MIM_DOCUMENT+10),
	MI_FLIPWORDS = (MIM_DOCUMENT+11),
};

enum {		// TOOLS menu
	MIM_TOOLS = 600,
//	MI_VERIFY = (MIM_TOOLS+1),
	MI_CHECK = (MIM_TOOLS+1),
	MI_RECONCILE = (MIM_TOOLS+2),
	MI_GENERATE = (MIM_TOOLS+3),
	MI_ALTER = (MIM_TOOLS+4),
	MI_SORT = (MIM_TOOLS+5),
	MI_COMPRESS = (MIM_TOOLS+6),
	MI_EXPAND = (MIM_TOOLS+7),
	MI_COUNT = (MIM_TOOLS+8),
	MI_STATISTICS = (MIM_TOOLS+9),
	MI_ABBREVIATIONS = (MIM_TOOLS+10),
	MI_FKEYS = (MIM_TOOLS+11),
	MI_FONTS = (MIM_TOOLS+12),
	MI_TAGS = (MIM_TOOLS+13),
	MI_GROUPS = (MIM_TOOLS+14),
	MI_SPLIT = (MIM_TOOLS+15),
};

enum {		// WINDOW menu
	MIM_WINDOWS = 700,
	MI_HIDEINACTIVE = (MIM_WINDOWS+4),
};

enum {				// document window toolbar items
	TB_NEWRECORD = 800,
	TB_LABELED,
	TB_DELETED,
	TB_VIEWALL,
	TB_FORMATTYPE,
	TB_FULLFORMAT,
	TB_DRAFTFORMAT,
	TB_STYLETYPE,
	TB_INDENTED,
	TB_RUNIN,
	TB_SORTTYPE,
	TB_ALPHASORT,
	TB_PAGESORT,
	TB_NOSORT,
	TB_FONT,
	TB_SIZE,
};

enum {			// record window toolbar items
	TB_PROPAGATE = 900,
	TB_BRACES,
	TB_ANGLES,
	TB_FLIPFULL,
	TB_FLIPHALF,
	TB_SWAPPAREN,
	TB_DEFFONT,
	TB_BOLD,
	TB_ITALIC,
	TB_UNDERLINE,
	TB_REVERT,
	TB_PREVRECORD,
	TB_NEXTRECORD,
	TB_ENTERRECORD
};

enum {			// label submenu items
	MI_LABEL0 = 1000,
	MI_LABEL1,
	MI_LABEL2,
	MI_LABEL3,
	MI_LABEL4,
	MI_LABEL5,
	MI_LABEL6,
	MI_LABEL7
};

enum {			// alignment submenu items
	MI_ALIGNNATURAL = 2000,
	MI_ALIGNLEFT,
	MI_ALIGNRIGHT,
};



