/*
 *  recordparams.h
 *  Cindex
 *
 *  Created by PL on 1/10/05.
 *  Copyright 2005 Indexing Research. All rights reserved.
 *
 */

typedef unsigned int RECN;

typedef struct {
	RECN num;		/* holds record number */
	RECN parent;		/* number of parent record */
	RECN lchild;		/* number of left child record */
	RECN rchild;		/* number of right child record */
	time_c time;		/* time of last change */
	char user[4];		/* up to four initials of user who last changed */
	unsigned ismod : 1;		/// unused
	unsigned isdel : 1;		/* true if record deleted */
	unsigned ismark : 1;	/* true if record marked */
	unsigned islock : 1;	// unused
	unsigned balance : 2;	/* holds balance of subtree on record */
	unsigned isgen : 1;		/* TRUE if autogenerated */
	unsigned isttag : 1;	/* TRUE if temporarily tagged */
	unsigned label : 3;		/* holds tag ID */
	short padding;			//  padding to align rtext
	char rtext[];			/* text of record */
} RECORD;

#define RECSIZE (sizeof(RECORD))

